version: '2'

services:

  fedora:
    image: a4neg/fedora-rdp
    build:
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}

    cpu_shares: 1023
    mem_limit: 32G
    shm_size: 128M
    stdin_open: true
    tty: true
    ports:
      - "3389:3389"

  fedora_tag:
    extends: fedora-rdp
    image: a4neg/fedora-rdp

